# Generated by Django 2.1.2 on 2019-05-16 07:29

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=app.models.upload_path, verbose_name='Image')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(default='tehran', max_length=255, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.CharField(default='iran', max_length=255, verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelimage',
            name='rel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Hotel', verbose_name='Hotel'),
        ),
        migrations.AddField(
            model_name='hotelimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
