# Generated by Django 2.1.2 on 2019-05-21 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190516_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='booked',
            field=models.URLField(blank=True, null=True, verbose_name='Booked at'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='rel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_image', to='app.Hotel', verbose_name='Hotel'),
        ),
    ]
